calculator/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'calculator'

urlpatterns = [
    path('cost/', views.Cost, name='cost'),
    path('Addtech/<int:tech_id>',views.Addtech,name='Addtech'),
    path('Done/',views.Done,name='Done'),
]

core/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.contrib.auth import views as auth_views
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', include('register.urls', namespace='register')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='register/password_reset.html'),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='register/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='register/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='register/password_reset_complete.html'),name='password_reset_complete'),
    path('', include('core.urls', namespace='core')),
    path('calculator/',include('calculator.urls',namespace='calculator'))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

calculator/models.py
from django.db import models
from django.db.models.deletion import CASCADE

class Category(models.Model):
    # options=(
    #     ('wireframes','wireframes'),
    #     ('frontend','frontend'),
    #     ('backend','backend'),
    #     ('frameworks','frameworks'),
    #     ('database','database'),
    #     ('cloud','cloud'),
    #     ('hosting','hosting'),
    #     ('Extra','Extra')
    # )
    cname=models.CharField(max_length=100)
    def __str__(self):
        return self.cname 

class Technology(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10,decimal_places=2,default=0)
    
    def __str__(self):
        return str(self.name)

class AddTech(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10,decimal_places=2,default=0)

    def __str__(self):
        return str(self.price)

calculator/forms.py
from django.db.models import fields
from django.forms import ModelForm
from .models import *

class addTech(ModelForm):
    class Meta:
        model=AddTech
        fields = ['name','price']
        

calculator/views.py
from django.http.response import HttpResponse
from django.shortcuts import render,redirect
from . models import Technology,Category
from django.db.models import Sum
from .forms import *
# from .forms import CalciForm

def Cost(request):
    catg = Category.objects.all()
    tech = Technology.objects.all()
    context= {
        'catg':catg,
        'tech':tech,
    }
    return render(request,'calculator/cost.html',context)

def Addtech(request,tech_id):
    tech1 = Technology.objects.filter(id=tech_id).first()
    price = tech1.price
    post=AddTech()
    post.name=tech1
    post.price = price
    post.save()
    add = AddTech.objects.all()
    count= AddTech.objects.all().count()
    sum = AddTech.objects.aggregate(Sum('price'))
    ans= sum['price__sum']
    context= {
        'add':add,
        'count':count,
        'ans':ans,

    }
    return render(request,'calculator/addusertech.html',context)

def Done(request):
    tech=AddTech.objects.all()
    tech.delete()
    
    return redirect('calculator:cost')

calculator/templates/calculator/addusertech.html
{% extends 'core/base.html' %}
{% load static %}


{% block breadcrumb %}
<li class="breadcrumb-item">Home</li>
<li class="breadcrumb-item">Calculator</li>
<li class="breadcrumb-item active">Project Estimation Calculator</li>
{% endblock breadcrumb%}
{% block content %}
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <strong>Project Estimation Calculator</strong>
        </div>
        <div class="card-body">
            <div class="col-sm-12">
                <h3>{{count}} Technology Added</h3>
                <table class="table table-striped table-success ">
                    <thead>
                        <tr>
                            <th scope="col">Technology</th>
                            <!-- <th scope="col">Price</th> -->
                        </tr>
                    </thead>
            
                    <tbody>
                        {% for t in add %}
                        <tr>
                            <td>{{t.name}}</td>
                            <!-- <td>Rs: {{t.price}}</td> -->
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <h3>*Minimum Price Estimated for the project: RS: {{ans}} </h3>
                <div class="text-center">
                    <a href='{% url "calculator:cost" %}' type="button" class="btn btn-outline-dark btn-sm mx-1 text-center">Add More Technology</a>
                    <a href='{% url "calculator:Done" %}' type="button" class="btn btn-outline-dark btn-sm mx-1 text-center">Done</a>
                </div>
                
                
            </div>

        </div>

    </div>
</div>
{% endblock %}

calculator/templates/calculator/cost.html
{% extends 'core/base.html' %}
{% load static %}


{% block breadcrumb %}
<li class="breadcrumb-item">Home</li>
<li class="breadcrumb-item">Calculator</li>
<li class="breadcrumb-item active">Project Estimation Calculator</li>
{% endblock breadcrumb%}
{% block content %}
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <strong>Project Estimation Calculator</strong>
        </div>
        <div class="card-body">
            <div class="col-sm-12">
            
                {% for c in catg %}
                <h4>{{c}}</h4>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Technology</th>
                            <!-- <th scope="col">Price</th> -->
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
            
                    <tbody>
                        {% for t in tech %}
                        {% if t.category == c %}
                        <tr>
                            <td>{{t.name}}</td>
                            <!-- <td>Rs: {{t.price}}</td> -->
                            <td>
                                <form action="{% url 'calculator:Addtech'  tech_id=t.id  %}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-outline-dark btn-sm mx-1">Add</button>
                                </form>
                                <!-- <a href='{% url "calculator:Addtech"  tech_id=t.id  %}' type="button" class="btn btn-outline-dark btn-sm mx-1">Add</a> -->
                            </td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
                {% endfor %}
            </div>

        </div>

    </div>
</div>
{% endblock %}