core/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.contrib.auth import views as auth_views
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', include('register.urls', namespace='register')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='register/password_reset.html'),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='register/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='register/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='register/password_reset_complete.html'),name='password_reset_complete'),
    path('', include('core.urls', namespace='core')),
    path('calculator/',include('calculator.urls',namespace='calculator'))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from django.urls.conf import include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'projects'

urlpatterns = [
    path('', views.projects, name='projects'),
    path('new-project/', views.newProject, name='new-project'),
    path('new-task/', views.newTask, name='new-task'),
    path('task/', views.task, name='task'),
    path('search/', views.search,name='search'),
    path('project/<int:project_id>/delete', views.delete_project, name = 'delete_project'),
    path('project/<int:project_id>/edit', views.edit_project, name = 'edit_project'),
    path('task/<int:task_id>/delete', views.delete_task, name = 'delete_task'),
    path('task/<int:task_id>/edit', views.edit_task, name = 'edit_task'),
    path('value/<int:project_id>', views.formset_view, name='formset_view'),
    path('task/<int:task_id>', views.form_view, name='form_view'),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


status = (
    ('1', 'Stuck'),
    ('2', 'Working'),
    ('3', 'Done'),
)

due = (
    ('1', 'On Due'),
    ('2', 'Overdue'),
    ('3', 'Done'),
)

# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=80)
    slug = models.SlugField('shortcut', blank=True)
    assign = models.ManyToManyField(User)
    efforts = models.DurationField()
    status = models.CharField(max_length=7, choices=status, default=1)
    dead_line = models.DateField()
    company = models.ForeignKey('register.Company', on_delete=models.CASCADE)
    complete_per = models.FloatField(max_length=2, validators = [MinValueValidator(0), MaxValueValidator(100)])
    description = models.TextField(blank=True)

    add_date = models.DateField(auto_now_add=True)
    upd_date = models.DateField(auto_now_add=False, auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return (self.name)

class Task(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    assign = models.ManyToManyField(User)
    task_name = models.CharField(max_length=80)
    status = models.CharField(max_length=7, choices=status, default=1)
    due = models.CharField(max_length=7, choices=due, default=1)

    class Meta:
        ordering = ['project', 'task_name']

    def __str__(self):
        return(self.task_name)

projects/forms.py
from django import forms
from django.utils.text import slugify
from .models import Task
from .models import Project
from register.models import Company
from django.contrib.auth.models import User

status = (
    ('1', 'Stuck'),
    ('2', 'Working'),
    ('3', 'Done'),
)

due = (
    ('1', 'On Due'),
    ('2', 'Overdue'),
    ('3', 'Done'),
)


class TaskRegistrationForm(forms.ModelForm):
    project = forms.ModelChoiceField(queryset=Project.objects.all())
    assign = forms.ModelMultipleChoiceField(queryset=User.objects.all())
    task_name = forms.CharField(max_length=80)
    status = forms.ChoiceField(choices=status)
    due = forms.ChoiceField(choices=due)

    class Meta:
        model = Task
        fields = '__all__'


    def save(self, commit=True):
        task = super(TaskRegistrationForm, self).save(commit=False)
        task.project = self.cleaned_data['project']
        task.task_name = self.cleaned_data['task_name']
        task.status = self.cleaned_data['status']
        task.due = self.cleaned_data['due']
        task.save()
        assigns = self.cleaned_data['assign']
        for assign in assigns:
            task.assign.add((assign))

        if commit:
            task.save()

        return task


    def __init__(self, *args, **kwargs):
        super(TaskRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['project'].widget.attrs['class'] = 'form-control'
        self.fields['project'].widget.attrs['placeholder'] = 'Social Name'
        self.fields['task_name'].widget.attrs['class'] = 'form-control'
        self.fields['task_name'].widget.attrs['placeholder'] = 'Name'
        self.fields['status'].widget.attrs['class'] = 'form-control'
        self.fields['status'].widget.attrs['placeholder'] = 'Email'
        self.fields['due'].widget.attrs['class'] = 'form-control'
        self.fields['due'].widget.attrs['placeholder'] = 'City'
        self.fields['assign'].widget.attrs['class'] = 'form-control'
        self.fields['assign'].widget.attrs['placeholder'] = 'Found date'


class ProjectRegistrationForm(forms.ModelForm):
    name = forms.CharField(max_length=80)
    # slug = forms.SlugField('shortcut')
    assign = forms.ModelMultipleChoiceField(queryset=User.objects.all())
    efforts = forms.DurationField()
    status = forms.ChoiceField(choices=status)
    dead_line = forms.DateField()
    company = forms.ModelChoiceField(queryset=Company.objects.all())
    complete_per = forms.FloatField(min_value=0, max_value=100)
    description = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Project
        fields = '__all__'


    def save(self, commit=True):
        Project = super(ProjectRegistrationForm, self).save(commit=False)
        Project.name = self.cleaned_data['name']
        Project.efforts = self.cleaned_data['efforts']
        Project.status = self.cleaned_data['status']
        Project.dead_line = self.cleaned_data['dead_line']
        Project.company = self.cleaned_data['company']
        Project.complete_per = self.cleaned_data['complete_per']
        Project.description = self.cleaned_data['description']
        Project.slug = slugify(str(self.cleaned_data['name']))
        Project.save()
        assigns = self.cleaned_data['assign']
        for assign in assigns:
            Project.assign.add((assign))

        if commit:
            Project.save()

        return Project


    def __init__(self, *args, **kwargs):
        super(ProjectRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['placeholder'] = 'Project Name'
        self.fields['efforts'].widget.attrs['class'] = 'form-control'
        self.fields['efforts'].widget.attrs['placeholder'] = 'Efforts'
        self.fields['status'].widget.attrs['class'] = 'form-control'
        self.fields['status'].widget.attrs['placeholder'] = 'Status'
        self.fields['dead_line'].widget.attrs['class'] = 'form-control'
        self.fields['dead_line'].widget.attrs['placeholder'] = 'Dead Line, type a date'
        self.fields['company'].widget.attrs['class'] = 'form-control'
        self.fields['company'].widget.attrs['placeholder'] = 'Company'
        self.fields['complete_per'].widget.attrs['class'] = 'form-control'
        self.fields['complete_per'].widget.attrs['placeholder'] = 'Complete %'
        self.fields['description'].widget.attrs['class'] = 'form-control'
        self.fields['description'].widget.attrs['placeholder'] = 'Type here the project description...'
        self.fields['assign'].widget.attrs['class'] = 'form-control'

class ProjectForm(forms.ModelForm):
    
    class Meta:
        model = Project
        fields = ('name', 'efforts', 'status', 'dead_line', 'complete_per')

class TaskForm(forms.ModelForm):
    
    class Meta:
        model = Task
        fields = ( 'task_name', 'status', 'due')

class ValueForm(forms.Form):
    No_of_days = forms.FloatField()

projects/views.py
from django.http.request import HttpRequest
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Avg
from django.db.models import Q
from django.forms import formset_factory
from projects.forms import ValueForm
from register.models import Project
from projects.models import Task
from projects.forms import TaskRegistrationForm
from projects.forms import ProjectRegistrationForm
from projects.forms import ProjectForm
from projects.forms import TaskForm

# Create your views here.
@login_required
def projects(request):
    projects = Project.objects.all()
    avg_projects = Project.objects.all().aggregate(Avg('complete_per'))['complete_per__avg']
    tasks = Task.objects.all()
    overdue_tasks = tasks.filter(due='2')
    context = {
        'avg_projects' : avg_projects,
        'projects' : projects,
        'tasks' : tasks,
        'overdue_tasks' : overdue_tasks,
    }
    return render(request, 'projects/projects.html', context)
@login_required
def newTask(request):
    if request.method == 'POST':
        form = TaskRegistrationForm(request.POST)
        context = {'form': form}
        if form.is_valid():
            form.save()
            created = True
            context = {
                'created': created,
                'form': form,
            }
            return render(request, 'projects/new_task.html', context)
        else:
            return render(request, 'projects/new_task.html', context)
    else:
        form = TaskRegistrationForm()
        context = {
            'form': form,
        }
        return render(request,'projects/new_task.html', context)
@login_required
def task(request):
    projects = Project.objects.all()
    avg_projects = Project.objects.all().aggregate(Avg('complete_per'))['complete_per__avg']
    tasks = Task.objects.all()
    overdue_tasks = tasks.filter(due='2')
    context = {
        'avg_projects' : avg_projects,
        'projects' : projects,
        'tasks' : tasks,
        'overdue_tasks' : overdue_tasks,
    }
    return render(request, 'projects/task.html', context)
@login_required
def newProject(request):
    if request.method == 'POST':
        form = ProjectRegistrationForm(request.POST)
        context = {'form': form}
        if form.is_valid():
            form.save()
            created = True
            form = ProjectRegistrationForm()
            context = {
                'created': created,
                'form': form,
            }
            return render(request, 'projects/new_project.html', context)
        else:
            return render(request, 'projects/new_project.html', context)
    else:
        form = ProjectRegistrationForm()
        context = {
            'form': form,
        }
        return render(request,'projects/new_project.html', context)
@login_required
def search(request):
    projects = Project.objects.all()
    avg_projects = Project.objects.all().aggregate(Avg('complete_per'))['complete_per__avg']
    query =None
    results =[]
    if request.method == 'GET':
        query=request.GET.get('search')
        results=Project.objects.filter(Q(name__icontains=query)| Q(description__icontains=query))
    context = {
            'query':query,
            'results':results,
            'avg_projects' : avg_projects,
            'projects' : projects,
    }
    return render(request,'projects/search.html',context)
@login_required
def delete_project(request, project_id):
    project = Project.objects.filter(pk = project_id)
    if project:
        project = Project.objects.get(pk = project_id)
        project.delete()
    return redirect('projects:projects')
@login_required
def edit_project(request, project_id):
    project = get_object_or_404(Project, pk = project_id)
    if request.method == 'POST':
        form = ProjectForm(request.POST, instance = project)
        if form.is_valid():
            project = form.save(commit = False)
            project.save()
            return redirect('projects:projects')
    else:
        form = ProjectForm(instance = project)

    return render(request, template_name = 'projects/edit_project.html', context = { 'form': form })
@login_required
def delete_task(request, task_id):
    task = Task.objects.filter(pk = task_id)
    if task:
        task = Task.objects.get(pk = task_id)
        task.delete()
    return redirect('projects:task')
@login_required
def edit_task(request, task_id):
    task = get_object_or_404(Task, pk = task_id)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance = task)
        if form.is_valid():
            task = form.save(commit = False)
            task.save()
            return redirect('projects:task')
    else:
        form = TaskForm(instance = task)

    return render(request, template_name = 'projects/edit_task.html', context = { 'form': form })

def formset_view(request,project_id):
    project = Project.objects.filter(id=project_id).first()
    assi = project.assign.all()
    FormSet = formset_factory(ValueForm, extra = assi.count())
    formset = FormSet(request.POST or None)
    values = []
    keys = []
    ans=0
    if formset.is_valid():
        sum=0
        for form in formset:
            values.append(100/form.cleaned_data['No_of_days'])
            sum=sum+100/form.cleaned_data['No_of_days']
        ans=round(100/sum)
    for i in range(assi.count()):
        keys.append(i+1)
    d=dict(zip(keys,values))
    context={
    'formset':formset,
    'ans':ans,
    'd':d,
    }
    return render(request, "projects/value.html", context)

def form_view(request,task_id):
    task = Task.objects.filter(id=task_id).first()
    assi = task.assign.all()
    FormSet = formset_factory(ValueForm, extra = assi.count())
    formset = FormSet(request.POST or None)
    ans=0
    if formset.is_valid():
        sum=0
        for form in formset:
            sum=sum+100/form.cleaned_data['value']
        ans=100/sum
    context={
        'formset':formset,
        'ans':ans,
        }
    return render(request, "projects/value.html", context)

projects/templates/projects/projects.html
{% extends 'core/base.html' %}
{% load static %}


{% block breadcrumb %}
<li class="breadcrumb-item">Home</li>
<li class="breadcrumb-item">Projects</li>
<li class="breadcrumb-item active">Views</li>
{% endblock breadcrumb%}
{% block content %}
<div class="col-md-12">
</div>
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <strong>{{ projects.count }} Active Projects</strong>
        </div>
        <div class="card-body">
            <div class="row">
                {% for project in projects %}
                <div class="col-12 col-md-6 col-lg-4">
                <div class="card mx-2">
                    <div class="card-body">
                        <div class="h4 m-0">
                            {{ project.dead_line }}
                            {% if project.status == '1' %}
                            <p class="text-right lead text-danger">Stuck</p>
                            {% elif project.status == '2' %}
                            <p class="text-right lead text-success">Working</p>
                            {% else %}
                            <p class="text-right lead text-info">Done</p>
                            {% endif %}
                        </div>
                        <div>{{ project.name }}</div>
                        <h6>Assigned Members {{project.assign.count}}</h6>
                        <br>
                        <a href='{% url "projects:edit_project" project_id=project.id %}' type="button" class="btn btn-outline-dark btn-sm mx-1 ">Update</a>
                        <a href='{% url "projects:delete_project" project_id=project.id %}' type="button" class="btn btn-outline-dark btn-sm mx-1 ">Delete</a>
                        <a href='{% url "projects:formset_view"  project_id=project.id  %}' type="button" class="btn btn-outline-dark btn-sm mx-1 ">Time calculator</a>
                        <p class="text-muted mb-0 text-right">{{ project.complete_per }}%</p>
                        <div class="progress progress-xs mb-3">
                            {% if project.complete_per < 30%}
                            <div class="progress-bar bg-danger role="progressbar" style="width: {{ project.complete_per }}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                            {% elif project.complete_per < 80%}
                            <div class="progress-bar bg-warning role="progressbar" style="width: {{ project.complete_per }}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                            {% else %}
                            <div class="progress-bar bg-success role="progressbar" style="width: {{ project.complete_per }}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                            {% endif %}
                        </div>
                        <small class="text-muted">{{ project.description|truncatechars:60 }}</small>
                    </div>
                </div>
                </div>
                {% endfor %}
            </div>
            <br>
        </div>
    </div>
</div>
{% endblock %}

<!-- <div>
    <a href="#" type="button" class="btn btn-outline-dark btn-sm mx-1">Update</button>
    <a href="#" type="button" class="btn btn-outline-dark btn-sm mx-1">Delete</button>
</div> -->

projects/templates/projects/task.html
{% extends 'core/base.html' %}
{% load static %}


{% block breadcrumb %}
<li class="breadcrumb-item">Home</li>
<li class="breadcrumb-item">Projects</li>
<li class="breadcrumb-item active">Views</li>
{% endblock breadcrumb%}
{% block content %}
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <strong>{{ tasks.count }} Active Tasks</strong>
        </div>
        <div class="card-body">
            <div class="row">

                <div class="col-sm-8">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="callout callout-dark">
                                <small class="text-muted">Tasks</small>
                                <br>
                                <strong class="h4">{{ tasks.count }}</strong>
                                <div class="chart-wrapper">
                                    <div class="chartjs-size-monitor"
                                        style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;">
                                        <div class="chartjs-size-monitor-expand"
                                            style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;">
                                            <div
                                                style="position:absolute;width:1000000px;height:1000000px;left:0;top:0">
                                            </div>
                                        </div>
                                        <div class="chartjs-size-monitor-shrink"
                                            style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;">
                                            <div style="position:absolute;width:200%;height:200%;left:0; top:0"></div>
                                        </div>
                                    </div>
                                    <canvas id="sparkline-chart-3" width="86" height="25" class="chartjs-render-monitor"
                                        style="display: block; width: 86px; height: 25px;"></canvas>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="callout callout-danger">
                                <small class="text-muted">Overdue Tasks </small>
                                <br>
                                <strong class="h4">{{ overdue_tasks.count }}</strong>
                                <div class="chart-wrapper">
                                    <div class="chartjs-size-monitor"
                                        style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;">
                                        <div class="chartjs-size-monitor-expand"
                                            style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;">
                                            <div
                                                style="position:absolute;width:1000000px;height:1000000px;left:0;top:0">
                                            </div>
                                        </div>
                                        <div class="chartjs-size-monitor-shrink"
                                            style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;">
                                            <div style="position:absolute;width:200%;height:200%;left:0; top:0"></div>
                                        </div>
                                    </div>
                                    <canvas id="sparkline-chart-4" width="86" height="25" class="chartjs-render-monitor"
                                        style="display: block; width: 86px; height: 25px;"></canvas>
                                </div>
                            </div>
                        </div>


                    </div>

                    <hr class="mt-0">
                    <!-- <ul class="horizontal-bars type-2">
                        <h4>Projects Status</h4>
                        <li>
                        <i class="fa fa-percent"></i>
                        <span class="title">Projects</span>
                        <span class="value">{{ avg_projects|floatformat }}%</span>
                        <div class="bars">
                            <div class="progress progress-xs">
                                <div class="progress-bar bg-warning" role="progressbar" style="width: {{ avg_projects|floatformat }}%" aria-valuenow="43" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                    </li>
                        <li class="divider"></li>
                        {% for project in projects %}
                        <li class="my-2">
                            {% if project.status == '1' %}
                            <span class="badge badge-danger" style="width: 50px;">Stuck</span>
                            {% elif project.status == '2' %}
                            <span class="badge badge-info" style="width: 50px;">Working</span>
                            {% else %}
                            <span class="badge badge-success" style="width: 50px;">Done!</span>
                            {% endif %}
                            <a href="#" style="text-decoration: none;"><span class="title ml-1">{{ project }}</span></a>

                            <span class="value"> <span class="text-muted small">deadline: </span>{{ project.dead_line }}
                                <span class="text-muted small">({{ project.complete_per }}%)</span>
                            </span>
                            <div class="bars">
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-success" role="progressbar"
                                        style="width: {{ project.complete_per }}%"
                                        aria-valuenow="{{ project.complete_per }}" aria-valuemin="0"
                                        aria-valuemax="100"></div>
                                </div>
                            </div>
                        </li>
                        {% endfor %}
                    </ul> -->
                </div>

            </div>

            <br>
            <div class="col-sm-12">
                {% for project in projects %}
                <h4>Your Tasks for {{ project }} project</h4>
                <ul class="horizontal-bars type-2">
                    <li class="my-2">
                        {% if project.status == '1' %}
                        <span class="badge badge-danger" style="width: 50px;">Stuck</span>
                        {% elif project.status == '2' %}
                        <span class="badge badge-info" style="width: 50px;">Working</span>
                        {% else %}
                        <span class="badge badge-success" style="width: 50px;">Done!</span>
                        {% endif %}
                        <span class="title ml-1">{{ project }}</span>

                        <span class="value"> <span class="text-muted small">deadline: </span>{{ project.dead_line }}
                            <span class="text-muted small">({{ project.complete_per }}%)</span>
                        </span>
                        <div class="bars">
                            <div class="progress progress-xs">
                                <div class="progress-bar bg-success" role="progressbar"
                                    style="width: {{ project.complete_per }}%"
                                    aria-valuenow="{{ project.complete_per }}" aria-valuemin="0"
                                    aria-valuemax="100"></div>
                            </div>
                        </div>
                    </li>
                </ul>
            
                {% if tasks|length == 0 %}
            
                <div class="alert alert-dark" role="alert">
                    No Tasks found!
                </div>
                {% else %}
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Task Name</th>
                            <th scope="col">Status</th>
                            <th scope="col">Due</th>
                            <th scope="col">Project</th>
                            <th scope="col">No of members assigned</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
            
                    <tbody>
                        {% for task in tasks %}
                        {% if task.project == project %}
                        <tr>
                            <td>{{task.task_name}}</td>
                            {% if task.status == '1' %}
                            <td>Stuck</td>
                            {% elif task.status == '2'%}
                            <td>Working</td>
                            {% else %}
                            <td>Done</td>
                            {% endif%}
                            {% if task.due == '1' %}
                            <td>on due</td>
                            {% elif task.due == '2'%}
                            <td>Overdue</td>
                            {% else %}
                            <td>Done</td>
                            {% endif%}
                            <td>{{task.project}}</td>
                            <td>{{task.assign.count}}</td>
                            <td>
                                <a href='{% url "projects:edit_task" task_id=task.id %}' type="button" class="btn btn-outline-dark btn-sm mx-1">Update</button>
                                <a href='{% url "projects:delete_task" task_id=task.id %}' type="button" class="btn btn-outline-dark btn-sm mx-1">Delete</button>
                                <a href='{% url "projects:form_view"  task_id=task.id  %}' type="button" class="btn btn-outline-dark btn-sm mx-1 ">Time calculator</a>
                            </td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
                {% endif %}
                {% endfor %}
            </div>

        </div>

    </div>
</div>
{% endblock %}

projects/templates/projects/value.html
{% extends 'core/base.html' %}
{% load static %}


{% block breadcrumb %}
<li class="breadcrumb-item">Home</li>
<li class="breadcrumb-item">Calculator</li>
<li class="breadcrumb-item active">Project Estimated Time Calculator</li>
{% endblock breadcrumb%}
{% block content %}
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <strong>Project Estimated Time Calculator</strong>
        </div>
        <div class="card-body">
            <div class="col-sm-12">
                <div class="text-center">
                    <form method="POST" enctype="multipart/form-data">
                        {{ formset.management_data }}
                        {% csrf_token %}
                        {{ formset.as_p }}
                        <input type="submit" value="Submit">
                    </form>
                    {% for key, value in d.items %}
                    <h5>Efficiency of user {{key}} : {{value}}</h5>
                    {% endfor %}
                    

                    <h4>Estimated Time For Completion Of Project: {{ans}} Days</h4>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}